language: python
sudo: true
python:
  - "3.6"
install:
  - pip install twilio
script: 
  - cp src/* test/
  - cd test
  - python test_spider.py
  - python test_spider.py
  - python test_tool.py
  - python test_tool.py
